name: Android CI

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        api-level: [21, 28, 34]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: ${{ matrix.api-level }}

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Build and Test
      run: |
        chmod +x ./gradlew
        ./gradlew build
        ./gradlew testDebugUnitTest

    - name: Code Coverage
      run: ./gradlew jacocoTestReport

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-api-${{ matrix.api-level }}
        path: app/build/reports/jacoco/
        retention-days: 7

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: continuous-integration
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run Quality Checks
      run: |
        chmod +x ./gradlew
        ./gradlew checkstyleDebug
        ./gradlew pmdDebug
        ./gradlew detekt

    - name: Upload Quality Reports
      uses: actions/upload-artifact@v4
      with:
        name: quality-reports
        path: |
          app/build/reports/checkstyle/
          app/build/reports/pmd/
          app/build/reports/detekt/
        retention-days: 7
